spring:
  profiles:
    active: prod

logging:
  # 1) logback 설정 파일로 강제 지정
  config: classpath:logback-spring.xml

  # 2) 최상위(root) 레벨을 원하는 만큼 올리기 (DEBUG, INFO 중 선택)
  level:
    root: DEBUG



# logging:
#   discord:
#     enabled: true
#     webhook-url: https://discord.com/api/webhooks/1372464453630558221/d7FNPuVXrdne7MzIB0ZrfunlcgaldOb9KxmWAjrxrsub7PsAuXHqOHhwMyTPUpTubIf-
#     config: classpath:logback-spring.xml