
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_REGION_STATIC}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus  # prometheus 엔드포인트도 노출
  metrics:
    export:
      prometheus:
        enabled: true         # Dev에서는 pull(scrape) 방식으로 Prometheus 사용
      otlp:
        enabled: true         # 동시에 OTLP로도 Collector에 전송 가능
        endpoint: http://10.1.3.26:4317  # 실제 Collector IP:Port
        protocol: http/protobuf
  tracing:
    sampling:
      probability: 1.0       # 100% 샘플링 (모든 요청에 대한 트레이스 수집)
